name: Build Binaries and Docker Image

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  build-binaries:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/ai-cli-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/ai-cli
          if [ "${{ matrix.goos }}" == "windows" ]; then mv dist/ai-cli-${{ matrix.goos }}-${{ matrix.goarch }} dist/ai-cli-${{ matrix.goos }}-${{ matrix.goarch }}.exe; fi

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ai-cli-binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/ai-cli-${{ matrix.goos }}-${{ matrix.goarch }}*

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-binaries

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build --file ./Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/ai-cli:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ai-cli:${{ github.sha }}

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/ai-cli:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ai-cli:${{ env.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ai-cli:${{ env.tag }}
